upstream robot_signal {
    server 127.0.0.1:4173 max_fails=2 fail_timeout=10s;
    server 127.0.0.1:4174 max_fails=2 fail_timeout=10s;
    server 127.0.0.1:4175 max_fails=2 fail_timeout=10s;
    server 127.0.0.1:4176 max_fails=2 fail_timeout=10s;
    server 127.0.0.1:4177 max_fails=2 fail_timeout=10s;
    server 127.0.0.1:4178 max_fails=2 fail_timeout=10s;
}
